// <auto-generated />
namespace passionProject_storeTickets2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PurchasePrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurchasePrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202206030531579_PurchasePrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
